### ISSUE TITLE
shadowing behavior should be the default

### ISSUE THREAD

**Issue by schanzer** [ds26gte/pyret-lang#4]
For example:
(define (f e) e)

**Comment by ds26gte** [comment]
Fixed in 99eb4b1. 

Shadowing behavior is indeed the default. This bug rather had to do with (just) the four constant identifiers {`false`, `true`, `pi`, `e`} being incapable being used as lexical variables. Now they can be so used.

N.B. `null` can also be used as lexical variable. `empty` however cannot: It is a true literal evaluating to itself. Do we want to change the empty literal to something like `#empty`, with the global variable `empty` bound to `#empty`?

**Comment by schanzer** [comment]
I think this is a good idea. Make it so. :)

**Comment by ds26gte** [comment]
Made it so in 17370ab.
